version: '3.8'

services:
  kombi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - kombi-db:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Istanbul
    env_file:
      - .env

volumes:
  kombi-db:
